name: Release Drafter

on:
  push:
    branches:
      - main
  # pull_request event is required only for autolabeler
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: self-hosted
    steps:
      - name: Calendar Version
        id: calver
        uses: emm035/calver@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          create_tag: false
          tag_prefix: '20'
      - uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.calver.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
